import type { DecisionFormValues } from "@/lib/decisions/form";

export type DecisionPreset = {
  id: "balanced" | "premium" | "surge" | "recovery";
  label: {
    zh: string;
    en: string;
  };
  summary: {
    zh: string;
    en: string;
  };
  posture: {
    zh: string;
    en: string;
  };
  values: Partial<DecisionFormValues>;
};

export const DECISION_PRESETS: DecisionPreset[] = [
  {
    id: "balanced",
    label: {
      zh: "均衡增长",
      en: "Balanced growth",
    },
    summary: {
      zh: "以稳健收益、品牌积累和服务兑现为主，适合大多数常规轮次。",
      en: "Balances yield, brand building, and service delivery for standard rounds.",
    },
    posture: {
      zh: "稳健",
      en: "Stable",
    },
    values: {
      priceBusinessTransient: 600,
      priceBusinessGroup: 540,
      priceLeisureTransient: 500,
      priceLeisureGroup: 435,
      priceGovernment: 400,
      priceOnlineOTA: 445,
      priceAirlineCrew: 320,
      priceLongStay: 355,
      marketingTotal: 86,
      mktBudgetBusinessTransient: 15,
      mktBudgetBusinessGroup: 12,
      mktBudgetLeisureTransient: 14,
      mktBudgetLeisureGroup: 11,
      mktBudgetGovernment: 8,
      mktBudgetOnlineOTA: 11,
      mktBudgetAirlineCrew: 5,
      mktBudgetLongStay: 10,
      channelDirect: 30,
      channelOTA: 28,
      channelTravelAgent: 12,
      channelCorporate: 20,
      channelGDS: 10,
      opexRoomsMaintenance: 31,
      opexFoodBeverage: 25,
      opexFrontDesk: 15,
      opexHousekeeping: 24,
      opexUtilities: 18,
      opexStaffTraining: 10,
      opexStaffWelfare: 8,
      opexSecurity: 6,
      opexIT: 10,
      capexTechnology: 2,
      capexFacilities: 1,
      esgEnergyInvestment: 32,
      esgWasteManagement: 32,
      esgCommunityEngagement: 22,
      esgEmployeeDiversity: 22,
      taxStrategy: "STANDARD",
    },
  },
  {
    id: "premium",
    label: {
      zh: "高收益商旅",
      en: "Premium business mix",
    },
    summary: {
      zh: "抬高高价值客群价格，强化直销、企业协议与技术支撑，追求 ADR 和净收益。",
      en: "Pushes ADR and net yield through premium pricing and direct-led channels.",
    },
    posture: {
      zh: "进攻",
      en: "Aggressive",
    },
    values: {
      priceBusinessTransient: 710,
      priceBusinessGroup: 650,
      priceLeisureTransient: 545,
      priceLeisureGroup: 465,
      priceGovernment: 410,
      priceOnlineOTA: 455,
      priceAirlineCrew: 325,
      priceLongStay: 370,
      marketingTotal: 92,
      mktBudgetBusinessTransient: 18,
      mktBudgetBusinessGroup: 17,
      mktBudgetLeisureTransient: 11,
      mktBudgetLeisureGroup: 8,
      mktBudgetGovernment: 7,
      mktBudgetOnlineOTA: 9,
      mktBudgetAirlineCrew: 4,
      mktBudgetLongStay: 18,
      channelDirect: 34,
      channelOTA: 18,
      channelTravelAgent: 8,
      channelCorporate: 26,
      channelGDS: 14,
      opexRoomsMaintenance: 32,
      opexFoodBeverage: 27,
      opexFrontDesk: 16,
      opexHousekeeping: 25,
      opexUtilities: 19,
      opexStaffTraining: 11,
      opexStaffWelfare: 9,
      opexSecurity: 6,
      opexIT: 12,
      capexTechnology: 5,
      capexFacilities: 3,
      capexESGGreen: 2,
      esgEnergyInvestment: 34,
      esgWasteManagement: 30,
      esgCommunityEngagement: 20,
      esgEmployeeDiversity: 24,
      taxStrategy: "STANDARD",
    },
  },
  {
    id: "surge",
    label: {
      zh: "假期冲量",
      en: "Demand surge",
    },
    summary: {
      zh: "通过休闲与 OTA 流量快速冲入住，但需要同步守住服务和现场执行。",
      en: "Targets leisure and OTA volume to push occupancy, with tighter execution demands.",
    },
    posture: {
      zh: "冲量",
      en: "Volume",
    },
    values: {
      priceBusinessTransient: 560,
      priceBusinessGroup: 500,
      priceLeisureTransient: 445,
      priceLeisureGroup: 390,
      priceGovernment: 380,
      priceOnlineOTA: 405,
      priceAirlineCrew: 300,
      priceLongStay: 330,
      marketingTotal: 98,
      mktBudgetBusinessTransient: 9,
      mktBudgetBusinessGroup: 8,
      mktBudgetLeisureTransient: 20,
      mktBudgetLeisureGroup: 15,
      mktBudgetGovernment: 7,
      mktBudgetOnlineOTA: 18,
      mktBudgetAirlineCrew: 5,
      mktBudgetLongStay: 16,
      channelDirect: 24,
      channelOTA: 38,
      channelTravelAgent: 16,
      channelCorporate: 14,
      channelGDS: 8,
      opexRoomsMaintenance: 31,
      opexFoodBeverage: 28,
      opexFrontDesk: 17,
      opexHousekeeping: 27,
      opexUtilities: 20,
      opexStaffTraining: 10,
      opexStaffWelfare: 9,
      opexSecurity: 6,
      opexIT: 9,
      capexFacilities: 2,
      esgEnergyInvestment: 30,
      esgWasteManagement: 29,
      esgCommunityEngagement: 20,
      esgEmployeeDiversity: 21,
      taxStrategy: "STANDARD",
    },
  },
  {
    id: "recovery",
    label: {
      zh: "修复回稳",
      en: "Recovery reset",
    },
    summary: {
      zh: "优先修复现金、服务和品牌底盘，适合上一轮经营承压后的回稳阶段。",
      en: "Stabilizes cash, service, and brand after a difficult round.",
    },
    posture: {
      zh: "修复",
      en: "Recovery",
    },
    values: {
      priceBusinessTransient: 585,
      priceBusinessGroup: 520,
      priceLeisureTransient: 470,
      priceLeisureGroup: 415,
      priceGovernment: 390,
      priceOnlineOTA: 435,
      priceAirlineCrew: 315,
      priceLongStay: 345,
      marketingTotal: 72,
      mktBudgetBusinessTransient: 12,
      mktBudgetBusinessGroup: 9,
      mktBudgetLeisureTransient: 11,
      mktBudgetLeisureGroup: 9,
      mktBudgetGovernment: 8,
      mktBudgetOnlineOTA: 8,
      mktBudgetAirlineCrew: 5,
      mktBudgetLongStay: 10,
      channelDirect: 32,
      channelOTA: 22,
      channelTravelAgent: 12,
      channelCorporate: 22,
      channelGDS: 12,
      opexRoomsMaintenance: 34,
      opexFoodBeverage: 24,
      opexFrontDesk: 17,
      opexHousekeeping: 28,
      opexUtilities: 18,
      opexStaffTraining: 12,
      opexStaffWelfare: 11,
      opexSecurity: 7,
      opexIT: 10,
      capexRenovation: 3,
      capexFurniture: 2,
      capexTechnology: 2,
      capexFacilities: 1,
      capexESGGreen: 1,
      newLoanAmount: 0,
      loanRepayment: 3,
      esgEnergyInvestment: 34,
      esgWasteManagement: 33,
      esgCommunityEngagement: 24,
      esgEmployeeDiversity: 25,
      taxStrategy: "COMPLIANCE_FIRST",
    },
  },
];

export function applyDecisionPreset(
  current: DecisionFormValues,
  preset: DecisionPreset
) {
  return {
    ...current,
    ...preset.values,
  } satisfies DecisionFormValues;
}
