import { DEFAULT_SIM_PARAMETERS, type SimParameters } from "@/lib/constants";

export type SimulationParameterCatalogEntry = {
  key: keyof SimParameters;
  label: string;
  description: string;
  unit: string;
  min: number;
  max: number;
  step: number;
  formulaIds: string[];
};

export const SIMULATION_PARAMETER_CATALOG: SimulationParameterCatalogEntry[] = [
  {
    key: "totalMarketDemandBase",
    label: "基础市场总需求",
    description: "在未考虑队伍数量时，全市场每月基础需求规模。",
    unit: "间夜",
    min: 1000,
    max: 12000,
    step: 50,
    formulaIds: ["market-demand"],
  },
  {
    key: "demandPerHotelBase",
    label: "单酒店基础需求",
    description: "用于按队伍数量放大市场容量，避免班级扩容后需求不足。",
    unit: "间夜",
    min: 100,
    max: 2500,
    step: 25,
    formulaIds: ["market-demand"],
  },
  {
    key: "totalRooms",
    label: "标准客房数",
    description: "用于说明默认酒店体量，供老师后续替换容量相关公式。",
    unit: "间",
    min: 50,
    max: 3000,
    step: 10,
    formulaIds: ["financial-outcome"],
  },
  {
    key: "daysInMonth",
    label: "月度经营天数",
    description: "决定每轮可供销售的理论经营天数。",
    unit: "天",
    min: 20,
    max: 31,
    step: 1,
    formulaIds: ["market-demand", "financial-outcome"],
  },
  {
    key: "maxRoomNightsPerMonth",
    label: "月度最大可售间夜",
    description: "用于对总售房量进行上限约束。",
    unit: "间夜",
    min: 1000,
    max: 50000,
    step: 100,
    formulaIds: ["financial-outcome"],
  },
  {
    key: "fbRevenueRatio",
    label: "餐饮收入系数",
    description: "按客房收入推算餐饮收入的比例。",
    unit: "比例",
    min: 0,
    max: 1,
    step: 0.01,
    formulaIds: ["financial-outcome"],
  },
  {
    key: "otherRevenueRatio",
    label: "其他收入系数",
    description: "按客房收入推算其他经营收入的比例。",
    unit: "比例",
    min: 0,
    max: 1,
    step: 0.01,
    formulaIds: ["financial-outcome"],
  },
  {
    key: "basePropertyTaxRate",
    label: "基础物业税率",
    description: "为老师后续接入更完整税制模型预留的参数入口。",
    unit: "比例",
    min: 0,
    max: 0.2,
    step: 0.001,
    formulaIds: ["financial-outcome"],
  },
  {
    key: "corporateTaxRate",
    label: "企业所得税率",
    description: "利润为正时的默认所得税率。",
    unit: "比例",
    min: 0,
    max: 0.5,
    step: 0.005,
    formulaIds: ["financial-outcome"],
  },
  {
    key: "vatRate",
    label: "增值税率",
    description: "为老师后续引入更细税费结构预留的参数入口。",
    unit: "比例",
    min: 0,
    max: 0.3,
    step: 0.001,
    formulaIds: ["financial-outcome"],
  },
  {
    key: "depreciationRate",
    label: "折旧率",
    description: "资本开支转化为折旧费用的默认速率。",
    unit: "比例",
    min: 0,
    max: 0.2,
    step: 0.001,
    formulaIds: ["financial-outcome"],
  },
  {
    key: "randomnessFactor",
    label: "随机扰动强度",
    description: "控制吸引力评分中的可重复扰动幅度，便于做平衡性测试。",
    unit: "比例",
    min: 0,
    max: 0.3,
    step: 0.005,
    formulaIds: ["appeal-scoring"],
  },
  {
    key: "competitionIntensity",
    label: "竞争强度",
    description: "控制队伍吸引力与平均分配之间的平滑程度。",
    unit: "比例",
    min: 0,
    max: 1,
    step: 0.01,
    formulaIds: ["appeal-scoring"],
  },
  {
    key: "brandDecayRate",
    label: "品牌衰减率",
    description: "品牌声誉在每轮自然衰减的比例。",
    unit: "比例",
    min: 0,
    max: 0.2,
    step: 0.001,
    formulaIds: ["guest-experience"],
  },
  {
    key: "conditionDecayRate",
    label: "资产状态衰减率",
    description: "物业与设施状态在每轮自然折损的比例。",
    unit: "比例",
    min: 0,
    max: 0.2,
    step: 0.001,
    formulaIds: ["guest-experience"],
  },
  {
    key: "serviceStrainThreshold",
    label: "服务承压阈值",
    description: "入住率高于该阈值后，前厅、客房与服务恢复压力会明显上升。",
    unit: "比例",
    min: 0.5,
    max: 0.98,
    step: 0.01,
    formulaIds: ["guest-experience", "financial-outcome"],
  },
  {
    key: "laborCostSensitivity",
    label: "人工成本敏感度",
    description: "控制高入住且人力投入不足时的加班、低效率与服务补救成本放大程度。",
    unit: "比例",
    min: 0,
    max: 0.6,
    step: 0.01,
    formulaIds: ["guest-experience", "financial-outcome"],
  },
  {
    key: "weatherEnergySensitivity",
    label: "天气能耗敏感度",
    description: "控制高温、寒潮等天气对酒店能源成本和 HVAC 负荷的影响程度。",
    unit: "比例",
    min: 0,
    max: 0.4,
    step: 0.01,
    formulaIds: ["financial-outcome"],
  },
  {
    key: "otaBillboardFactor",
    label: "OTA 展示溢出系数",
    description: "反映 OTA 展示带来的轻微品牌曝光和间接预订增益，默认保持较弱。",
    unit: "比例",
    min: 0,
    max: 0.2,
    step: 0.005,
    formulaIds: ["appeal-scoring"],
  },
  {
    key: "directBookingLift",
    label: "直销收益提升系数",
    description: "反映直销、协议与 GDS 在品牌和技术支撑下的收益管理优势。",
    unit: "比例",
    min: 0,
    max: 0.25,
    step: 0.005,
    formulaIds: ["appeal-scoring", "financial-outcome"],
  },
  {
    key: "facilitiesUpsellFactor",
    label: "设施会务溢价系数",
    description: "控制会议、宴会和公共区域升级对团体需求及附加收入的放大程度。",
    unit: "比例",
    min: 0,
    max: 0.3,
    step: 0.005,
    formulaIds: ["appeal-scoring", "financial-outcome"],
  },
] as const;

export function getDefaultSimulationParameters() {
  return { ...DEFAULT_SIM_PARAMETERS } satisfies SimParameters;
}
